server:
  port: 8761

spring:
  application:
    name: service-registry
  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: localhost
  server:
    eviction-interval-timer-in-ms: 60000
    response-cache-update-interval-ms: 30000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: [info,health]
    jmx:
      exposure:
        include: [info,health,prometheus,metrics,threaddump]